<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="../static/css/style.css" />

    <title>Corvus Corax</title>
</head>
<body>
<h1>Details</h1>
<nav class="navbar">
    <ul>
        <li><a href="bird-list.ftlh">Home</a></li>
        <li><a href="about.html">About</a></li>
        <li><a href="bird-details.ftlh">Details</a></li>
        <li><a href="bird-create.ftlh">New Bird</a></li>
        <li><a href="bird-update.ftlh">Update Bird</a> </li>
    </ul>
</nav>
<main>
    <h1>Corvus Corax: the Common Raven</h1>
    <pre>
        The Common Raven is a large, black, passerine bird. It is the most widespread corvid, found across the world in the northern hemisphere.
    </pre
    >
    <br />
    <img
            src="https://upload.wikimedia.org/wikipedia/commons/d/d8/CorvusCoraxIUCN.svg"
            alt="worldwide raven distribution"
    /><br />
    <pre>
        Passerine Birds are those in the order Passeriformes, from the Latin "sparrow-shaped", which includes more than half
        of all bird species. They are also known as "perching birds" because of the arrangement of their toes (three forward
        and one backward) which facilitates their ability to perch.
    </pre
    >
    <img
            src="https://upload.wikimedia.org/wikipedia/commons/a/af/Parking_Lot_Raven_Curious_2019-10-29.jpg"
            alt="a curious raven"
    /><br />
    <pre>
        It is one of the largest corvids, and it is the heaviest passerine bird. <br>
    </pre>
    <img
            src="https://upload.wikimedia.org/wikipedia/commons/9/91/Corvus_corax_clarionensis%2C_Point_Reyes_National_Seashore.jpg"
            alt="beach trip"
    /><br />
    <pre>
        Common Ravens are omnivorous, and have coexisted with humanity for thousands of years. Their versatile and opportunistic
        feeding habits have lead to them being considered pests, as they will feed on grains and fruits grown by farmers, and
        human food waste, alongside carrion, smaller birds and animals, and insects.
    </pre
    >
    <img
            src="https://upload.wikimedia.org/wikipedia/commons/2/2f/Corvus_corax_tibetanus.jpg"
            alt="Corvus_corax_tibetanus"
    /><br />
    <pre>
        Ravens typically mate for life, though some have been observed participating in infidelity. As ravens are some of
        the most intelligent birds, I believe it is our duty to teach them the Christian faith, so that these cheating
        birds know the damage to their souls they commit by galavanting with, by raven standards, married women.
      </pre>
</main>
</body>
</html>
